'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace CRUD

    Partial Public Class productsEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=productsEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Clients() As DbSet(Of Clients)
        Public Overridable Property Products() As DbSet(Of Products)
        Public Overridable Property SaleItems() As DbSet(Of SaleItems)
        Public Overridable Property Sales() As DbSet(Of Sales)
    
    End Class

End Namespace
